### ISSUE TITLE
Not drill down to multilevel object check

### ISSUE THREAD

**Issue by jayakummar** [ZEdwin/ZTCT#2]
It is not showing all objects associated with function group.let us say, FG has multiple FMs but this report shows only main includes in the function group

**Comment by ZEdwin** [comment]
This won't be changed... It is near impossible to find ALL associated objects. It would be a never-ending story. It has to end somewhere... I have included a search on all Data Dictionary objects that will first select ALL custom DD-objects that are not yet transported. Then checks if an untransported DD-object is used in the transport list, but not included in the list itself.
This is done to prevent dumps that will happen because, for example, a program or function uses an element that is NOT in the transport itself, but has been transported to the test environment somewhere in the past, but still hasn't been moved to the production environment. That is the main reason why dumps will occur in production after transporting a series of transports (even when checked thoroughly)
