### ISSUE TITLE
Importing file in offline mode is not working

### ISSUE THREAD

**Issue by hakimred** [ZEdwin/ZTCT#3]
I have downloaded the file and trying to import offline but the file is not getting loaded..Can you let me know how to import this program in offline mode into my system. thanks.

**Comment by ZEdwin** [comment]
I assume the problem is related to SAPLINK? All I can do is to provide the basic info about, and links to SAPLINK. If SAPLINK is installed correctly, loading and activating the ZTCT-nugget shouldn't be a problem.

Source:
[https://github.com/sapmentors/SAPlink](https://github.com/sapmentors/SAPlink)
The version you'll need can be found under the releases tab.
Please note that there is still an old wiki page on the internet, that will link to an old version of SAPLINK. That version (on Assembla) is outdated. Make sure you installed the GITHUB version...

The most clear and easy Installation Guide I found was this one:
[SAPLINK Installation](http://rene.turnheim.com/saplink/saplink-installation/)
It's a very nice Blog with just the information that people need to install it easily.
